### ISSUE TITLE
Score repeatedly getting Incrementing

### ISSUE THREAD

**Issue by jahnavijanaki** [jayasuryat/BallTrap-Issues#2]
While in the "new high score" screen kill and relaunch the app and watch the score get increase.

1. Play the game and create a high score.
2. While in the new high score screen close the app.
3. Again open the app.
4. Observe the score.

Ideally, the score should be left as is, but the score is getting incremented every time on kill and relaunch.

**Comment by JayaSuryaT** [comment]
Thanks for catching this @jahnavijanaki, that's a major issue.
I'll make sure to patch this up in the next version.

**Comment by KumarBusem** [comment]
I'm also facing the same issue

**Comment by KumarBusem** [comment]
Love you jahnavi

**Comment by jayasuryat** [comment]
Hey, thank you for reporting this issue.
This issue has been taken care of, expect to get the fix in the next build soon.
