### ISSUE TITLE
Loosing progress in the current level after temporarily closing the app.

### ISSUE THREAD

**Issue by bhagath555** [JayaSuryaT/BallTrap-Issues#6]
While playing the game, if I move to other app without totally closing the game, loosing the progress i made in that particular level. This is not the case when I completely close the game.

**To Reproduce**
1. Open the game 
2. Draw some lines
3. Press home button
4. Go back to the game.
5. There you have the same lavel but without the lines you drew earlier.

This is not the case when we kill the game, completely.

**Comment by jayasuryat** [comment]
Great catch, @bhagath555.
I just tried this out, and, oh snap! it got reproduced the first time only.

I'll investigate and get this fixed in the next release.

Thank you for reporting the issue and giving nice and descriptive steps to reproduce, you are awesome ✌️.

**Comment by jayasuryat** [comment]
Hey @bhagath555, thank you for reporting this issue.
This issue has been taken care of, expect to get fix in the next build soon.
